name:                journey
version:             0.1.0.0
github:              "zivia/journey"
license:             BSD3
author:              "Troy Squillaci"
maintainer:          "troysquillaci@gmail.com"
copyright:           "Troy Squillaci"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zivia/journey#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- time

library:
  source-dirs: src

executables:
  journey-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - journey

tests:
  journey-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - journey
